FROM node:lts-alpine as client-builder

WORKDIR /app

ENV ENVIRONMENT=production

COPY ./package.json ./yarn.lock ./.yarnrc.yml ./

COPY ./.yarn ./.yarn

RUN yarn install --immutable

COPY . .

RUN yarn build

FROM caddy as runner

COPY --from=client-builder /app/dist /static/client
COPY ./Caddyfile /etc/caddy/Caddyfile