FROM node:alpine as build
# update and install the latest dependencies for the alpine version
RUN apk update && apk upgrade
# set work dir as app
WORKDIR /app
# copy the nuxt project package json and package json lock if available 
COPY package.json yarn.lock ./
# install all the project dependencies
RUN  yarn install
# copy all other project files to working directory
COPY . ./
# build the nuxt project to generate the artifacts in .output directory
CMD [ "yarn", "dev" ]