stages:
  - dockerize
  - deploy

.base_rules:
  rules:
    - &staging_tag
      if: $CI_COMMIT_TAG =~ /^v\d+-beta$/
      variables:
        ENVIRONMENT: "staging"
        APP_VERSION: $CI_COMMIT_TAG
    - &prod_tag
      if: $CI_COMMIT_TAG =~ /^v\d+$/
      variables:
        ENVIRONMENT: "production"
        APP_VERSION: $CI_COMMIT_TAG

dockerize:
  stage: dockerize
  image: docker:25
  services:
    - docker:25-dind
  environment:
    name: $ENVIRONMENT
    url: $ENVIRONMENT_URL
  variables:
    # Extra slash '/' is needed properly append the project path see docker-compose.yml
    REGISTRY_PATH: $CI_REGISTRY/$CI_PROJECT_PATH/
    VERSION: $CI_ENVIRONMENT_SLUG
    COMMIT_REF: $CI_COMMIT_TAG
  script:
    - mv $ENV_FILE ./.env
    - export REGISTRY_PATH=$(echo "$REGISTRY_PATH" | tr '[:upper:]' '[:lower:]')
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker compose build
    - docker compose push
  rules:
    - *staging_tag
    - *prod_tag

deploy:
  stage: deploy
  image: docker:25
  services:
    - docker:25-dind
  environment:
    name: $ENVIRONMENT
    url: $ENVIRONMENT_URL
  before_script:
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - mv $ENV_FILE ./prod/.env
    - ssh-add <(echo "$SSH_PRIVATE_KEY" | tr -d '\r')
    - cd prod
    - sh docker_deploy.sh
  rules:
    - *staging_tag
    - *prod_tag
