stages:
  - dockerize
  - deploy
  # - deploy

.base_rules:
  rules:
    - &staging_tag
      if: $CI_COMMIT_TAG =~ /^v\d+-beta$/
      variables:
        ENVIRONMENT: "staging"
        ENVIRONMENT_URL: "https://staging.onroad.one"
        APP_VERSION: $CI_COMMIT_TAG
    - &prod_tag
      if: $CI_COMMIT_TAG =~ /^v\d+$/
      variables:
        ENVIRONMENT: "production"
        ENVIRONMENT_URL: "https://onroad.one"
        APP_VERSION: $CI_COMMIT_TAG

dockerize:
  stage: dockerize
  image: docker:25
  services:
    - docker:25-dind
  environment:
    name: $ENVIRONMENT
    url: $ENVIRONMENT_URL
  variables:
    # Extra slash '/' is needed properly append the project path see docker-compose.yml
    REGISTRY_PATH: $CI_REGISTRY/$CI_PROJECT_PATH/
    VERSION: $CI_ENVIRONMENT_SLUG
    COMMIT_REF: $CI_COMMIT_SHORT_SHA
  script:
    - export REGISTRY_PATH=$(echo "$REGISTRY_PATH" | tr '[:upper:]' '[:lower:]')
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker compose build
    - docker compose push
  rules:
    # - *staging_tag
    - *prod_tag

deploy:
  stage: deploy
  environment:
    name: $ENVIRONMENT
    url: $ENVIRONMENT_URL
  before_script:
    - mkdir -p ~/.ssh
    - echo "$SSH_SECRET_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - eval $(ssh-agent -s)
    - ssh-add ~/.ssh/id_ed25519
    - ssh-keyscan $DROPLET_IP >> ~/.ssh/known_hosts
  script:
    - ssh user@$DROPLET_IP "cd onroad && git pull"
  rules:
    - *staging_tag
    - *prod_tag
