stages:
  - dockerize
  # - deploy

.base_rules:
  rules:
    - &staging_tag
      if: $CI_COMMIT_TAG =~ /^v\d+-beta$/
      variables:
        ENVIRONMENT: "staging"
        ENVIRONMENT_URL: "https://staging.onroad.one"
        APP_VERSION: $CI_COMMIT_TAG
    - &prod_tag
      if: $CI_COMMIT_TAG =~ /^v\d+$/
      variables:
        ENVIRONMENT: "production"
        ENVIRONMENT_URL: "https://onroad.one"
        APP_VERSION: $CI_COMMIT_TAG

dockerize:
  stage: dockerize
  image: docker:25
  services:
    - docker:25-dind
  environment: $ENVIRONMENT
  variables:
    # Extra slash '/' is needed properly append the project path see docker-compose.yml
    REGISTRY_PATH: $CI_REGISTRY/$CI_PROJECT_PATH/
    VERSION: $CI_ENVIRONMENT_SLUG
  script:
    - export REGISTRY_PATH=$(echo "$REGISTRY_PATH" | tr '[:upper:]' '[:lower:]')
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker compose build
    - docker compose push
  rules:
    - *staging_tag
    - *prod_tag
# deploy:
#   stage: deploy
#   environment:
#     name: $ENVIRONMENT
#     url: $ENVIRONMENT_URL
#   before_script:
#     - wget https://storage.googleapis.com/kubernetes-release/release/v1.20.2/bin/linux/amd64/kubectl
#     - chmod +x ./kubectl
#     - mv ./kubectl /usr/local/bin/kubectl
#     - kubectl config get-contexts
#   script:
#     - kubectl config use-context $CI_PROJECT_PATH:marketplace-$ENVIRONMENT
#     - kubectl rollout restart deployment/mandix-api-app -n $ENVIRONMENT
#   rules:
#     - *staging_tag
#     - *prod_tag
