version: "3.9"

services:
  client:
    image: onroadclient:dev
    container_name: or_client_dev
    build:
      context: ./client
      dockerfile: Dockerfile.client.dev
    restart: unless-stopped
    volumes:
      - ./client:/app
      - /app/node_modules/
    environment:
      VITE_API_DOMAIN: ${DOMAIN_NAME}
      VITE_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    depends_on:
      - django
      - hasura

  django:
    image: onroadapi:dev
    container_name: or_django_dev
    build:
      dockerfile: ./Dockerfile.api.dev
    restart: unless-stopped
    volumes:
      - ./caddy/static:/app/static
      - .:/app
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db

  worker:
    image: onroadapi:dev
    container_name: or_worker_dev
    build:
      dockerfile: ./Dockerfile.api.dev
    command: python manage.py rundramatiq
    restart: unless-stopped
    volumes:
      - .:/app
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
      - rabbitmq

  caddy:
    restart: always
    image: onroadcaddy:dev
    build:
      context: ./caddy
      dockerfile: Dockerfile.caddy
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./caddy/cert.crt:/etc/pki/tls/certs/cert.crt
      - ./caddy/cert.key:/etc/pki/tls/private/cert.key
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - TLS=${TLS}
      - TLS_KEY=${TLS_KEY}
    container_name: or_caddy_dev
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
      - hasura

  db:
    image: postgis/postgis:16-master
    container_name: or_database
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  rabbitmq:
    image: rabbitmq:3-management
    container_name: or_rabbitmq
    restart: always
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}

  hasura:
    container_name: or_hasura
    image: onroadhasura:dev
    build:
      context: ./hasura
      dockerfile: Dockerfile.hasura
    restart: always
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata
    depends_on:
      - "db"
      - "django"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256","key":"${JWT_SECRET_KEY}","claims_namespace":"user_claims","claims_format":"json"}'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
      HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT: 120
      API_HOST: "http://django:9000"

volumes:
  postgres:
  rabbitmq:
  caddy_data:
  caddy_config:
