# Generated by Django 5.0.1 on 2024-01-24 16:14

import core.utils.random
import core.utils.time
import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.functions
import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('estb_year', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'makes',
            },
        ),
        migrations.CreateModel(
            name='PriceItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('EX', 'Ex-Showroom Price'), ('TCS', 'Tax Collected at Source'), ('RTO', 'Regional Transport Office'), ('IN', 'Insurance'), ('EW', 'Extended Warranty'), ('BK', 'Basic Kit'), ('FT', 'Fast Tag'), ('LBT', 'Local Body Taxes'), ('OA', 'Other Accessories'), ('CP', 'Consumer Promotion'), ('MI', 'Miscellaneous'), ('DI', 'Discount'), ('SU', 'Subsidy')], max_length=3)),
                ('type', models.CharField(choices=[('CR', 'Credit'), ('DB', 'Debit')], max_length=2)),
            ],
            options={
                'db_table': 'price_items',
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('SED', 'Sedan'), ('SUV', 'SUV'), ('CRS', 'Crossover'), ('HAT', 'Hatchback'), ('PCK', 'Pickup Truck'), ('MTC', 'Motorcycle'), ('VAN', 'Van'), ('CON', 'Convertible'), ('ATV', 'ATV'), ('BIC', 'Bicycle'), ('MO', 'Moped')], max_length=3)),
            ],
            options={
                'db_table': 'vehicle_types',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('google_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('apple_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('has_contributed', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.city')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
                ('mime_type', models.CharField(blank=True, max_length=50)),
                ('size', models.PositiveIntegerField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Attachments',
                'db_table': 'attachments',
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('AC', 'Accepted'), ('RJ', 'Rejected')], default='PD', max_length=2)),
                ('quoted_on', models.DateField()),
                ('dealership_name', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('remark', models.TextField(blank=True, null=True)),
                ('attachments', models.ManyToManyField(blank=True, to='core.attachment')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contributions',
            },
        ),
        migrations.CreateModel(
            name='ContributionPriceItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_no', models.PositiveSmallIntegerField(default=1)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contribution')),
                ('price_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.priceitem')),
            ],
            options={
                'db_table': 'contribution_price_items',
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, default=core.utils.time.get_refresh_token_expires_in, null=True)),
                ('client', models.CharField(default='web', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'refresh_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country')),
            ],
            options={
                'db_table': 'states',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.state'),
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('launch_date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('fuel_type', models.CharField(choices=[('PT', 'Petrol'), ('DL', 'Diesel'), ('CG', 'CNG'), ('EL', 'Electric'), ('HB', 'Hybrid')], max_length=2)),
                ('transmission', models.CharField(choices=[('MT', 'Manual Transmission'), ('SMT', 'Sequential Manual Transmission'), ('AMT', 'Automated Manual Transmission'), ('AT', 'Traditional Automatic Transmission'), ('DCT', 'Dual-Clutch Transmission'), ('CVT', 'Continuously Variable Transmission'), ('S-A', 'Semi-Automatic Transmission'), ('CVT-TC', 'CVT with Torque Converter'), ('DSG', 'Direct-Shift Gearbox'), ('PSH', 'Power Split Hybrid Transmission'), ('E-CVT', 'Electronic Continuously Variable Transmission'), ('ASG', 'Automated Sequential Gearbox'), ('HST', 'Hydrostatic Transmission'), ('IVT', 'Infinitely Variable Transmission')], default='MT', max_length=6)),
                ('description', models.TextField()),
                ('specifications', models.JSONField(blank=True, default=dict, null=True)),
                ('manufacturer_link', models.URLField(blank=True, max_length=255, null=True)),
                ('attachments', models.ManyToManyField(blank=True, to='core.attachment')),
            ],
            options={
                'db_table': 'variants',
            },
        ),
        migrations.AddField(
            model_name='contribution',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.variant'),
        ),
        migrations.CreateModel(
            name='VariantColor',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('hex_code', models.CharField(blank=True, max_length=7, null=True)),
                ('attachments', models.ManyToManyField(blank=True, to='core.attachment')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.variant')),
            ],
            options={
                'db_table': 'variant_colors',
            },
        ),
        migrations.AddField(
            model_name='contribution',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.variantcolor'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.make')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehicletype')),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
        migrations.AddField(
            model_name='variant',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehicle'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('UP', 'Upvote'), ('DN', 'Downvote')], max_length=2)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contribution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'votes',
            },
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('otp', models.CharField(default=core.utils.random.generate_otp, max_length=6)),
                ('expires_at', models.DateTimeField(default=core.utils.time.get_otp_expires_at)),
                ('used', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('EM', 'Email'), ('PH', 'Phone')], default='EM', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'otps',
                'ordering': ['-created_at'],
                'unique_together': {('otp', 'user', 'expires_at', 'type')},
            },
        ),
        migrations.CreateModel(
            name='PasswordChangeRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField(default=core.utils.time.get_password_change_request_expires_at)),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Password Change Requests',
                'db_table': 'password_change_requests',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'expires_at')},
            },
        ),
        migrations.AddConstraint(
            model_name='contributionpriceitem',
            constraint=models.CheckConstraint(check=models.Q(('value__gte', '0')), name='contribution_value_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='contributionpriceitem',
            constraint=models.UniqueConstraint(fields=('contribution', 'serial_no'), name='contribution_serial_no_unique'),
        ),
        migrations.AddConstraint(
            model_name='contributionpriceitem',
            constraint=models.UniqueConstraint(fields=('contribution', 'price_item'), name='contribution_price_item_unique'),
        ),
        migrations.AddConstraint(
            model_name='refreshtoken',
            constraint=models.UniqueConstraint(fields=('user', 'client'), name='one_token_per_user_client'),
        ),
        migrations.AlterUniqueTogether(
            name='variantcolor',
            unique_together={('variant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('contribution', 'user')},
        ),
    ]
