# Generated by Django 5.0.1 on 2024-01-18 17:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('EX', 'Ex-Showroom Price'), ('TCS', 'Tax Collected at Source'), ('RTO', 'Regional Transport Office'), ('IN', 'Insurance'), ('EW', 'Extended Warranty'), ('BK', 'Basic Kit'), ('FT', 'Fast Tag'), ('LBT', 'Local Body Taxes'), ('OA', 'Other Accessories'), ('CP', 'Consumer Promotion'), ('MI', 'Miscellaneous'), ('DI', 'Discount'), ('SU', 'Subsidy')], max_length=3)),
                ('type', models.CharField(choices=[('CR', 'Credit'), ('DB', 'Debit')], max_length=2)),
            ],
            options={
                'db_table': 'price_items',
            },
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='accessories',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='ex_showroom',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='misc',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='rto',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='subsidies',
        ),
        migrations.CreateModel(
            name='ContributionPriceItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_no', models.PositiveSmallIntegerField(default=1)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contribution')),
                ('price_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.priceitem')),
            ],
            options={
                'db_table': 'contribution_price_items',
            },
        ),
        migrations.AddConstraint(
            model_name='contributionpriceitem',
            constraint=models.CheckConstraint(check=models.Q(('value__gte', '0')), name='contribution_value_non_negative'),
        ),
        migrations.AlterUniqueTogether(
            name='contributionpriceitem',
            unique_together={('contribution', 'price_item', 'serial_no')},
        ),
    ]
