# Generated by Django 5.0.1 on 2024-01-27 09:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contribution_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('AC', 'Accepted'), ('RJ', 'Rejected')], db_default=models.Value('PD'), max_length=2),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='total',
            field=models.DecimalField(db_default=models.Value(Decimal('0')), decimal_places=2, max_digits=10),
        ),
    ]
