# Generated by Django 5.0.1 on 2024-01-27 09:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_contribution_status_alter_contribution_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="downvotes",
            field=models.IntegerField(
                db_default=models.Value(Decimal("0")), default=Decimal("0")
            ),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="status",
            field=models.CharField(
                choices=[("PD", "Pending"), ("AC", "Accepted"), ("RJ", "Rejected")],
                db_default=models.Value("PD"),
                default="PD",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="total",
            field=models.DecimalField(
                db_default=models.Value(Decimal("0")),
                decimal_places=2,
                default=Decimal("0"),
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="upvotes",
            field=models.IntegerField(
                db_default=models.Value(Decimal("0")), default=Decimal("0")
            ),
        ),
        migrations.AlterField(
            model_name="contributionpriceitem",
            name="serial_no",
            field=models.PositiveSmallIntegerField(
                db_default=models.Value(1), default=1
            ),
        ),
        migrations.AlterField(
            model_name="variant",
            name="specifications",
            field=models.JSONField(
                blank=True, db_default=models.Value(str({})), default=dict, null=True
            ),
        ),
        migrations.AlterField(
            model_name="variant",
            name="transmission",
            field=models.CharField(
                choices=[
                    ("MT", "Manual Transmission"),
                    ("SMT", "Sequential Manual Transmission"),
                    ("AMT", "Automated Manual Transmission"),
                    ("AT", "Traditional Automatic Transmission"),
                    ("DCT", "Dual-Clutch Transmission"),
                    ("CVT", "Continuously Variable Transmission"),
                    ("S-A", "Semi-Automatic Transmission"),
                    ("CVT-TC", "CVT with Torque Converter"),
                    ("DSG", "Direct-Shift Gearbox"),
                    ("PSH", "Power Split Hybrid Transmission"),
                    ("E-CVT", "Electronic Continuously Variable Transmission"),
                    ("ASG", "Automated Sequential Gearbox"),
                    ("HST", "Hydrostatic Transmission"),
                    ("IVT", "Infinitely Variable Transmission"),
                ],
                db_default=models.Value("MT"),
                default="MT",
                max_length=6,
            ),
        ),
    ]
