# Generated by Django 5.0.1 on 2024-01-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_contribution_downvotes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="priceitem",
            name="serial_no",
            field=models.PositiveSmallIntegerField(
                db_default=models.Value(1), default=1
            ),
        ),
    ]
