# Generated by Django 5.0.1 on 2024-01-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_attachment_height_attachment_width_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='height',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='width',
        ),
        migrations.AddField(
            model_name='attachment',
            name='mime_type',
            field=models.CharField(default='image/jpeg', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachment',
            name='size',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
