# Generated by Django 5.0.1 on 2024-01-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_attachment_height_remove_attachment_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='mime_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='size',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='core.attachment'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='core.attachment'),
        ),
        migrations.AlterField(
            model_name='variantcolor',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='core.attachment'),
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
