# Generated by Django 5.0.1 on 2024-01-20 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_attachment_mime_type_alter_attachment_size_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contributionpriceitem',
            unique_together={('contribution', 'serial_no')},
        ),
    ]
