# Generated by Django 5.0.1 on 2024-01-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_contributionpriceitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contributionpriceitem',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='contributionpriceitem',
            constraint=models.UniqueConstraint(fields=('contribution', 'serial_no'), name='contribution_serial_no_unique'),
        ),
        migrations.AddConstraint(
            model_name='contributionpriceitem',
            constraint=models.UniqueConstraint(fields=('contribution', 'price_item'), name='contribution_price_item_unique'),
        ),
    ]
