# Generated by Django 5.0.1 on 2024-01-29 09:03

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_file_attachment_url_attachment_etag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Attachments'},
        ),
        migrations.AddField(
            model_name='attachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AddField(
            model_name='attachment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
