# Generated by Django 5.0.1 on 2024-01-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_attachment_options_attachment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='url',
            field=models.URLField(),
        ),
    ]
