# Generated by Django 5.0.1 on 2024-01-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_contributionpriceitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_contributions',
            field=models.BooleanField(default=False),
        ),
    ]
