# Generated by Django 5.0.1 on 2024-01-20 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_has_contributions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='has_contributions',
            new_name='has_contributed',
        ),
    ]
