# Generated by Django 5.0.1 on 2024-01-21 05:26

import core.utils.time
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_has_contributions_user_has_contributed'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('expires_at', models.DateTimeField(default=core.utils.time.get_refresh_token_expires_in)),
                ('client', models.CharField(default='web', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'refresh_tokens',
            },
        ),
        migrations.AddConstraint(
            model_name='refreshtoken',
            constraint=models.UniqueConstraint(fields=('user', 'expires_at', 'client'), name='refresh_token_unique'),
        ),
    ]
