# Generated by Django 5.0.1 on 2024-01-21 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_refreshtoken_refreshtoken_refresh_token_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='refreshtoken',
            name='refresh_token_unique',
        ),
        migrations.AddConstraint(
            model_name='refreshtoken',
            constraint=models.UniqueConstraint(condition=models.Q(('expires_at__gt', datetime.datetime(2024, 1, 21, 5, 34, 33, 984233, tzinfo=datetime.timezone.utc))), fields=('user', 'client'), name='unique_user_client_refresh_token'),
        ),
    ]
