# Generated by Django 5.0.1 on 2024-01-22 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_refreshtoken_refresh_token_unique_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refreshtoken',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='refreshtoken',
            name='unique_user_client_refresh_token',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='refreshtoken',
            constraint=models.UniqueConstraint(condition=models.Q(('expires_at__gt', datetime.datetime(2024, 1, 22, 6, 21, 1, 863934, tzinfo=datetime.timezone.utc))), fields=('user', 'client'), name='unique_user_client_refresh_token'),
        ),
    ]
