# Generated by Django 5.0.1 on 2024-02-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_variant_slug_alter_variant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='slug',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
