# Generated by Django 5.0.1 on 2024-01-22 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_refreshtoken_unique_user_client_refresh_token_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='refreshtoken',
            name='unique_user_client_refresh_token',
        ),
        migrations.AddConstraint(
            model_name='refreshtoken',
            constraint=models.UniqueConstraint(condition=models.Q(('expires_at__gt', datetime.datetime(2024, 1, 22, 6, 21, 29, 685219, tzinfo=datetime.timezone.utc))), fields=('user', 'client'), name='unique_user_client_refresh_token'),
        ),
    ]
