# Generated by Django 5.0.1 on 2024-01-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_refreshtoken_unique_user_client_refresh_token_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='refreshtoken',
            name='unique_user_client_refresh_token',
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='refreshtoken',
            constraint=models.UniqueConstraint(fields=('user', 'client', 'is_valid'), name='one_valid_refresh_token_per_client'),
        ),
    ]
