# Generated by Django 5.0.1 on 2024-02-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_make_code_alter_vehicletype_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make',
            name='code',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='code',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
