# Generated by Django 5.0.1 on 2024-01-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_refreshtoken_unique_user_client_refresh_token_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='refreshtoken',
            name='one_valid_refresh_token_per_client',
        ),
        migrations.RemoveField(
            model_name='refreshtoken',
            name='is_valid',
        ),
        migrations.AddConstraint(
            model_name='refreshtoken',
            constraint=models.UniqueConstraint(fields=('user', 'client'), name='one_token_per_client_per_user'),
        ),
    ]
