# Generated by Django 5.0.1 on 2024-01-24 04:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0019_remove_refreshtoken_one_valid_refresh_token_per_client_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="refreshtoken",
            name="provider",
            field=models.CharField(
                choices=[("OR", "Onroad"), ("GO", "Google"), ("AP", "Apple")],
                default="OR",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="refreshtoken",
            name="token",
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
