# Generated by Django 5.0.1 on 2024-02-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='client',
            field=models.CharField(db_default=models.Value('web'), max_length=255),
        ),
    ]
