# Generated by Django 5.0.1 on 2024-02-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_usertoken_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertoken',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'User Tokens'},
        ),
        migrations.AddField(
            model_name='usertoken',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
