# Generated by Django 5.0.1 on 2024-01-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_refreshtoken_provider_alter_refreshtoken_token'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='refreshtoken',
            name='one_token_per_client_per_user',
        ),
        migrations.AddConstraint(
            model_name='refreshtoken',
            constraint=models.UniqueConstraint(fields=('user', 'client', 'provider'), name='one_token_per_user_client_provider'),
        ),
    ]
