# Generated by Django 5.0.1 on 2024-02-04 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_usertoken_options_usertoken_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Otp',
        ),
    ]
