# Generated by Django 5.0.1 on 2024-01-24 04:10

import core.utils.time
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_refreshtoken_one_token_per_client_per_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=core.utils.time.get_refresh_token_expires_in, null=True),
        ),
    ]
