# Generated by Django 5.0.1 on 2024-02-04 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_delete_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordChangeRequest',
        ),
    ]
