# Generated by Django 5.0.1 on 2024-01-24 04:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_refreshtoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
