# Generated by Django 5.0.2 on 2024-02-13 05:53

import django.contrib.postgres.functions
import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_delete_passwordchangerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='downvotes',
            field=models.IntegerField(db_default=Decimal('0'), default=Decimal('0')),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('AC', 'Accepted'), ('RJ', 'Rejected')], db_default='PD', default='PD', max_length=2),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='total',
            field=models.DecimalField(db_default=Decimal('0'), decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='upvotes',
            field=models.IntegerField(db_default=Decimal('0'), default=Decimal('0')),
        ),
        migrations.AlterField(
            model_name='contributionpriceitem',
            name='serial_no',
            field=models.PositiveSmallIntegerField(db_default=1, default=1),
        ),
        migrations.AlterField(
            model_name='priceitem',
            name='serial_no',
            field=models.PositiveSmallIntegerField(db_default=1, default=1),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='client',
            field=models.CharField(db_default='web', max_length=255),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='type',
            field=models.CharField(choices=[('OT', 'OTP'), ('VC', 'Verifier Code'), ('PR', 'Password Reset'), ('RF', 'Refresh')], db_default='VC', max_length=2),
        ),
        migrations.AlterField(
            model_name='variant',
            name='specifications',
            field=models.JSONField(blank=True, db_default='{}', default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='transmission',
            field=models.CharField(choices=[('MT', 'Manual Transmission'), ('SMT', 'Sequential Manual Transmission'), ('AMT', 'Automated Manual Transmission'), ('AT', 'Traditional Automatic Transmission'), ('DCT', 'Dual-Clutch Transmission'), ('CVT', 'Continuously Variable Transmission'), ('S-A', 'Semi-Automatic Transmission'), ('CVT-TC', 'CVT with Torque Converter'), ('DSG', 'Direct-Shift Gearbox'), ('PSH', 'Power Split Hybrid Transmission'), ('E-CVT', 'Electronic Continuously Variable Transmission'), ('ASG', 'Automated Sequential Gearbox'), ('HST', 'Hydrostatic Transmission'), ('IVT', 'Infinitely Variable Transmission')], db_default='MT', default='MT', max_length=6),
        ),
        migrations.CreateModel(
            name='UserPassKeys',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_key', models.CharField(max_length=255)),
                ('credential_id', models.TextField(max_length=255)),
                ('sign_count', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Passkeys',
                'db_table': 'user_passkeys',
            },
        ),
    ]
