# Generated by Django 5.0.1 on 2024-01-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_user_apple_id_user_google_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="apple_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="google_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
