# Generated by Django 5.0.1 on 2024-01-24 10:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_user_apple_id_alter_user_google_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='refreshtoken',
            name='one_token_per_user_client_provider',
        ),
        migrations.RemoveField(
            model_name='refreshtoken',
            name='provider',
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddConstraint(
            model_name='refreshtoken',
            constraint=models.UniqueConstraint(fields=('user', 'client'), name='one_token_per_user_client'),
        ),
    ]
