# Generated by Django 5.0.2 on 2024-02-13 06:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_userpasskeys_credential_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpasskeys',
            name='sign_count',
            field=models.PositiveIntegerField(db_default=Decimal('0'), default=Decimal('0')),
        ),
    ]
