# Generated by Django 5.0.1 on 2024-01-24 14:10

import django.contrib.postgres.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshtoken',
            name='test',
            field=models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, unique=True),
        ),
    ]
