# Generated by Django 5.0.2 on 2024-02-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_delete_refreshtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpasskeys',
            name='sign_count',
        ),
        migrations.AddField(
            model_name='userpasskeys',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='userpasskeys',
            name='credential_id',
            field=models.BinaryField(unique=True),
        ),
    ]
