# Generated by Django 5.0.1 on 2024-01-24 14:15

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_refreshtoken_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshtoken',
            name='xyz',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False, unique=True),
        ),
    ]
