# Generated by Django 5.0.2 on 2024-02-13 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_userpasskeys_sign_count_userpasskeys_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpasskeys',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'User Passkeys'},
        ),
    ]
