# Generated by Django 5.0.2 on 2024-03-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_userpasskeys_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='status',
            field=models.CharField(choices=[('PD', '⏱️ Pending'), ('AC', '✅ Accepted'), ('RJ', '❌ Rejected')], db_default='PD', default='PD', max_length=2),
        ),
    ]
