SET check_function_bodies = false;
INSERT INTO public.variants (id, launch_date, name, fuel_type, transmission, description, specifications, manufacturer_link, vehicle_id) VALUES ('7965067e-dac3-4b60-ba6b-9b8c7e719c72', '2022-09-04', 'Okinawa Praise Pro 2022', 'EL', 'AT', 'The Okinawa PraisePro is equipped with a 2.7 kWh BLDC motor. It takes 2-3 hours to achieve a full charge for its battery, offering a claimed range of 88 km per charge. The model is available in one variant, STD.', '{"gps": "No", "tyre": "90/90-12 Tubeless (Front/Rear)", "speed": "56 kmph", "wheel": "Stylish Aluminum Alloy Wheel", "battery": "2.08 kWh Lithium-ion (Detachable Battery)", "voltage": "72V", "floor_mat": "Stylish Body Coloured", "headlight": "LED with DRL Function", "back_light": "Unique Design with LED rear Winkers", "controller": "E-ABS (Electronic- Assisted Braking System) with regenerative energy", "dimensions": "1970X715X1165mm", "peak_power": "2700 W", "suspension": "Front- Hydraulic Telescopic Rear- Double Shocker with dual tube technology", "brake_lever": "CNC Machined with Lever Adjustment", "seat_height": "800mm", "speedometer": "Digital", "brake_system": "FR- Disc | RR- Disc", "key_features": "Central Locking with Anti-theft Alarm, Keyless Entry, Find My Scooter Function, Mobile Charging USB Port, Motor Walking Assistance (Front/Reverse Motion)", "charging_time": "2-3 HRs", "motor_warranty": "3 Yrs/30,000KMs (whichever is earlier)***", "battery_warranty": "3 Years", "ground_clearance": "175mm", "loading_capacity": "150Kg", "range_per_charge": {"name": "81 km/Charge (Sports Mode)", "description": "Under Ideal Test Conditions - Specific Range Depends Upon Riding Condition and Road Condition"}, "climbing_approval": "Approved at 7 degrees", "arai_icat_approved": "Yes", "road_side_assistance": "Yes (Optional)", "charger_specification": "Micro-Charger with Auto Cut Function", "mobile_app_connectivity": "No"}', 'https://okinawascooters.com/scooters/praisepro', 'b4680840-0baa-47c4-9226-ac1f38b17037');
INSERT INTO public.variants (id, launch_date, name, fuel_type, transmission, description, specifications, manufacturer_link, vehicle_id) VALUES ('af665d7a-3816-4ded-bb8c-57b114588a1a', '2024-01-01', 'Hyndai Creta SX (O) 1.5 Diesel AT 2024', 'DL', 'AT', '# 2024 Hyundai Creta Facelift Overview
The 2024 Hyundai Creta facelift has been launched in India, introducing bolder styling, enhanced features, and three engine options in the popular mid-size SUV segment. Here''s a brief summary:
## Key Updates:
- **Refreshed Design:**
  - New grille, headlights, bumpers, and a more muscular stance.
- **Feature-packed:**
  - Panoramic sunroof, ventilated seats, ADAS (Advanced Driver Assistance Systems), and a fully digital instrument cluster.
- **Three Engine Choices:**
  - 1.5L naturally aspirated petrol, 1.5L turbocharged petrol, and 1.5L diesel.
  - Available with manual, automatic, and DCT transmissions.
- **Competitive Pricing:**
  - Starting at Rs. 10.99 lakhs (ex-showroom).
  - Comparable to rivals like Kia Seltos, Maruti Suzuki Grand Vitara, and Toyota Urban Cruiser Hyryder.
## Overall Impression:
The 2024 Creta facelift builds on its predecessor''s strengths, featuring a sharper look, a tech-laden interior, and diverse powertrain options. It continues to be a formidable player in the Indian SUV market, providing value, style, and a range of features suitable for urban driving and occasional off-road adventures.', '{"price": "Rs. 13.09 Lakh onwards", "engine": "1482 to 1497 cc", "fuel_type": "Petrol & Diesel", "transmission": "Manual & Automatic", "seating_capacity": "5 Seater"}', 'https://www.hyundai.com/in/en/find-a-car/creta/highlights', '408b40a3-9830-4537-8257-f331e6ed83b3');
